# File generated by cdo from CONTRIBUTING.md; DO NOT EDIT.

SHELL=bash
.SHELLFLAGS=-e -o pipefail -c

.PHONY: __help__
__help__:
	@echo 'Usage: make [target]'
	@echo ''
	@echo 'Targets:'
	@echo '  all      Run relevant tasks'
	@echo '  build    Build custom k6 with extension'
	@echo '  clean    Clean the working directory'
	@echo '  doc      Generate API documentation'
	@echo '  format   Format the go source codes'
	@echo '  lint     Run the linter'
	@echo '  makefile Generate the Makefile'
	@echo '  security Run security checks'
	@echo '  test     Run the tests'

# Run relevant tasks
.PHONY: all
all: clean format lint security test build makefile

# Build custom k6 with extension
.PHONY: build
build: 
	@(\
		xk6 build --with github.com/grafana/xk6-client-prometheus-remote=.;\
	)

# Clean the working directory
.PHONY: clean
clean: 
	@(\
		rm -rf coverage.txt ./k6 ./k6.exe ./build ./node_modules ./bun.lockb;\
	)

# Generate API documentation
.PHONY: doc
doc: 
	@(\
		bun x typedoc --out build/docs;\
	)

# Format the go source codes
.PHONY: format
format: 
	@(\
		go fmt ./...;\
	)

# Run the linter
.PHONY: lint
lint: 
	@(\
		golangci-lint run ./...;\
		xk6 lint;\
	)

# Generate the Makefile
.PHONY: makefile
makefile: 
	@(\
		cdo --makefile Makefile;\
	)

# Run security checks
.PHONY: security
security: 
	@(\
		gosec -quiet ./...;\
		govulncheck ./...;\
	)

# Run the tests
.PHONY: test
test: 
	@(\
		go test -count 1 -race -coverprofile=coverage.txt -timeout 60s ./...;\
	)

