# File generated by cdo from CONTRIBUTING.md; DO NOT EDIT.

SHELL=bash
.SHELLFLAGS=-e -o pipefail -c

# k6-ci golangci-lint config. `make lint` downloads .golangci.yml from
# grafana/k6-ci at the ref pinned in $(WORKFLOW). See grafana/k6-ci/README.md.
WORKFLOW    ?= .github/workflows/all.yml
K6_CI_REF   := $(shell grep -oE 'grafana/k6-ci/[^@[:space:]]+@[A-Za-z0-9._/-]+' $(WORKFLOW) | head -n1 | cut -d@ -f2)
LINT_CONFIG ?= .golangci.yml

.PHONY: __help__
__help__:
	@echo 'Usage: make [target]'
	@echo ''
	@echo 'Targets:'
	@echo '  all      Run relevant tasks'
	@echo '  build    Build custom k6 with extension'
	@echo '  clean    Clean the working directory'
	@echo '  doc      Generate API documentation'
	@echo '  format   Format the go source codes'
	@echo '  lint     Run the linter'
	@echo '  makefile Generate the Makefile'
	@echo '  security Run security checks'
	@echo '  test     Run the tests'

# Run relevant tasks
.PHONY: all
all: clean format lint security test build makefile

# Build custom k6 with extension
.PHONY: build
build: 
	@(\
		xk6 build --with github.com/grafana/xk6-client-prometheus-remote=.;\
	)

# Clean the working directory
.PHONY: clean
clean: 
	@(\
		rm -rf coverage.txt ./k6 ./k6.exe ./build ./node_modules ./bun.lockb;\
	)

# Generate API documentation
.PHONY: doc
doc: 
	@(\
		bun x typedoc --out build/docs;\
	)

# Format the go source codes
.PHONY: format
format: 
	@(\
		go fmt ./...;\
	)

# Run the linter
.PHONY: lint
lint: 
	@(\
		curl -fsSL https://raw.githubusercontent.com/grafana/k6-ci/$(K6_CI_REF)/.golangci.yml -o $(LINT_CONFIG);\
		go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@$$(head -n1 $(LINT_CONFIG) | tr -d '# ') run --config=$(LINT_CONFIG) ./...;\
		xk6 lint;\
	)

# Generate the Makefile
.PHONY: makefile
makefile: 
	@(\
		cdo --makefile Makefile;\
	)

# Run security checks
.PHONY: security
security: 
	@(\
		gosec -quiet ./...;\
		govulncheck ./...;\
	)

# Run the tests
.PHONY: test
test: 
	@(\
		go test -count 1 -race -coverprofile=coverage.txt -timeout 60s ./...;\
	)
